/**
 * Hand-authored exercises the source dataset lacks.
 *
 * free-exercise-db is broad but skews to gym equipment. It contains no jumping
 * jacks, no burpee, no wall sit, no pike push-up, and almost nothing for
 * bodyweight vertical pushing or pulling. Without these, a no-equipment plan
 * cannot fill several pattern slots at all -- which would break the core
 * promise of the app. These fill the gaps.
 *
 * They carry no photos (the source's images are not ours to remap onto a
 * different movement), so the UI falls back to a cue-forward layout.
 */
import type { Exercise } from "../src/types.ts";

type Draft = Omit<Exercise, "id"> & { id: string };

const ex = (
  id: string,
  name: string,
  rest: Partial<Draft> & Pick<Draft, "pattern" | "cues" | "defaults">
): Draft =>
  ({
    id,
    name,
    requires: [],
    primaryMuscles: [],
    secondaryMuscles: [],
    kind: "reps",
    level: "beginner",
    mechanic: "compound",
    contraindications: [],
    isJumping: false,
    isLoud: false,
    dynamic: true,
    spaceNeeded: "tight",
    unilateral: false,
    images: [],
    steps: [],
    chainId: null,
    chainRank: null,
    core: true,
    ...rest,
  }) as Draft;

const reps = (sets: number, r: number, restSec: number) => ({ sets, reps: r, restSec });
const time = (sets: number, durationSec: number, restSec: number) => ({
  sets,
  durationSec,
  restSec,
});

export const SUPPLEMENTS: Draft[] = [
  /* ---------------- gait / conditioning ---------------- */
  ex("Jumping_Jacks", "Jumping Jacks", {
    pattern: "gait",
    kind: "time",
    primaryMuscles: ["calves"],
    secondaryMuscles: ["shoulders", "quadriceps"],
    isJumping: true,
    isLoud: true,
    contraindications: ["knees"],
    cues: ["Land softly through the whole foot", "Keep knees soft, never locked out"],
    steps: [
      "Stand tall with your feet together and your arms relaxed at your sides.",
      "Jump your feet out to a little wider than your shoulders as you sweep both arms overhead.",
      "Land on the balls of your feet first and let the heels settle, keeping the knees soft.",
      "Jump the feet back together and bring the arms back down in the same rhythm.",
      "Breathe steadily and keep the contacts quiet rather than fast.",
    ],
    defaults: time(2, 40, 20),
  }),
  ex("March_In_Place", "March in Place", {
    pattern: "gait",
    kind: "time",
    primaryMuscles: ["quadriceps"],
    cues: ["Drive the knee to hip height", "Stay tall, ribs stacked over hips"],
    steps: [
      "Stand tall with your feet under your hips and your ribs stacked over your pelvis.",
      "Drive one knee up to hip height, keeping the standing leg long.",
      "Swing the opposite arm forward as the knee comes up.",
      "Place the foot down softly and repeat on the other leg.",
      "Keep the pace even; this is a warm-up, not a sprint.",
    ],
    defaults: time(2, 40, 20),
  }),
  ex("High_Knees", "High Knees", {
    pattern: "gait",
    kind: "time",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["calves", "abdominals"],
    isJumping: true,
    isLoud: true,
    contraindications: ["knees"],
    cues: ["Stay on the balls of your feet", "Quick, light contacts with the floor"],
    steps: [
      "Stand tall with your feet under your hips and your weight on the balls of your feet.",
      "Drive one knee up to hip height and immediately swap.",
      "Keep contacts light and quick, landing under your hips rather than in front.",
      "Pump the arms in time with the legs, elbows bent to ninety degrees.",
      "Stay upright; if you start leaning back, slow the cadence down.",
    ],
    defaults: time(2, 30, 30),
  }),
  ex("Burpee", "Burpee", {
    pattern: "gait",
    primaryMuscles: ["quadriceps", "chest"],
    secondaryMuscles: ["abdominals", "shoulders"],
    isJumping: true,
    isLoud: true,
    spaceNeeded: "normal",
    level: "intermediate",
    contraindications: ["knees", "wrists", "lower-back"],
    cues: ["Plant both hands before stepping back", "Stand fully tall at the top"],
    steps: [
      "Stand with your feet shoulder width apart.",
      "Squat down and plant both hands on the floor just outside your feet.",
      "Step or jump both feet back into a straight plank, hips level with the shoulders.",
      "Lower the chest to the floor if you are pressing, then push back up.",
      "Jump or step the feet back to your hands and stand fully tall.",
      "Finish each rep standing upright before starting the next one.",
    ],
    defaults: reps(3, 8, 60),
  }),

  /* ---------------- squat ---------------- */
  ex("Wall_Sit", "Wall Sit", {
    pattern: "squat",
    kind: "time",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["glutes"],
    contraindications: ["knees"],
    cues: ["Thighs parallel, back flat to the wall", "Push through the heels, breathe steadily"],
    steps: [
      "Stand with your back flat against a wall and your feet about two foot-lengths out.",
      "Slide down the wall until your thighs are parallel to the floor.",
      "Set your knees directly over your ankles, not past your toes.",
      "Press your whole back into the wall and let your arms hang or rest on your thighs.",
      "Push through the heels and breathe steadily for the full hold.",
    ],
    defaults: time(2, 40, 45),
  }),
  // Also deliberately knee-safe: the bench caps depth. See Assisted_Squat.
  ex("Bodyweight_Box_Squat", "Box Squat to Bench", {
    pattern: "squat",
    requires: ["bench"],
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["glutes"],
    cues: ["Sit back to the box, don't drop", "Stand up without rocking forward"],
    steps: [
      "Stand in front of a bench or box with your feet shoulder width apart.",
      "Push the hips back and sit down under control until you touch the bench.",
      "Keep the weight in your mid-foot and your chest tall as you sit.",
      "Pause on the bench for a beat without rocking backwards.",
      "Drive through the floor and stand up without leaning your chest forward.",
    ],
    defaults: reps(3, 12, 60),
  }),
  // Deliberately carries no knee contraindication: holding a support and
  // limiting depth is the standard knee-friendly squat regression. Together
  // with the box squat below, this is the ONLY thing that keeps the squat
  // slot fillable for someone who flagged their knees -- every dataset squat
  // is excluded for them. Do not add "knees" here without providing another
  // knee-safe squat, or the pattern falls through to lunge and then fails.
  ex("Assisted_Squat", "Assisted Squat", {
    pattern: "squat",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["glutes"],
    chainId: "squat-bw",
    chainRank: 1,
    cues: ["Hold a doorframe for balance only", "Sit between the hips, chest tall"],
    steps: [
      "Hold a doorframe, a post, or a suspension strap at about chest height.",
      "Set your feet shoulder width apart with the toes turned slightly out.",
      "Sit down between your hips, using the support only for balance, not to pull.",
      "Go as deep as you can while keeping your heels down and your chest tall.",
      "Drive through the whole foot to stand, squeezing the glutes at the top.",
    ],
    defaults: reps(2, 10, 60),
  }),
  ex("Pistol_Squat", "Pistol Squat", {
    pattern: "squat",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["glutes", "abdominals"],
    level: "expert",
    unilateral: true,
    core: false,
    chainId: "squat-bw",
    chainRank: 5,
    contraindications: ["knees"],
    cues: ["Reach the arms forward to counterbalance", "Control the descent, no collapsing"],
    steps: [
      "Stand on one leg with the other leg held straight out in front of you.",
      "Reach both arms forward to counterbalance.",
      "Sit back and down slowly, keeping the heel of the standing foot flat.",
      "Descend as far as you can control, then reverse without collapsing.",
      "Stand all the way up before starting the next rep.",
    ],
    defaults: reps(3, 5, 90),
  }),

  /* ---------------- hinge ---------------- */
  ex("Bodyweight_Good_Morning", "Bodyweight Good Morning", {
    pattern: "hinge",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["glutes", "lower-back"],
    contraindications: ["lower-back"],
    cues: ["Push the hips back, shins vertical", "Stop when the hamstrings tighten"],
    steps: [
      "Stand with your feet hip width apart and your hands lightly behind your head.",
      "Take a breath and brace your midsection.",
      "Push your hips straight back, letting your chest travel forward as one piece.",
      "Keep your shins vertical and your back flat the whole way.",
      "Stop when you feel the hamstrings tighten, then drive the hips forward to stand.",
    ],
    defaults: reps(2, 12, 45),
  }),
  // Not unilateral: marching alternates legs inside the set, so pausing it to
  // "switch sides" would be nonsense.
  ex("Glute_Bridge_March", "Glute Bridge March", {
    pattern: "hinge",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "abdominals"],
    cues: ["Keep the hips level as you lift", "Squeeze the glutes, not the lower back"],
    steps: [
      "Lie on your back with your knees bent and your feet flat, close to your hips.",
      "Drive through your heels and lift your hips until your body is a straight line.",
      "Hold that height and lift one knee toward your chest without dropping the hip.",
      "Place the foot back down and lift the other knee the same way.",
      "Keep the hips level and square throughout; that is the whole point of the drill.",
    ],
    defaults: reps(3, 10, 45),
  }),

  /* ---------------- lunge ---------------- */
  ex("Reverse_Lunge", "Reverse Lunge", {
    pattern: "lunge",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["glutes", "hamstrings"],
    unilateral: true,
    contraindications: ["knees"],
    cues: ["Step back and drop the back knee", "Keep the front shin near vertical"],
    steps: [
      "Stand tall with your feet under your hips.",
      "Step one foot straight back and lower until the back knee is just off the floor.",
      "Keep the front shin close to vertical and the front heel planted.",
      "Stay upright rather than folding over the front leg.",
      "Push through the front heel to bring the back foot home and stand tall.",
    ],
    defaults: reps(3, 10, 60),
  }),
  ex("Bulgarian_Split_Squat", "Bulgarian Split Squat", {
    pattern: "lunge",
    requires: ["bench"],
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["glutes"],
    unilateral: true,
    level: "intermediate",
    contraindications: ["knees"],
    cues: ["Front foot far enough forward to stay vertical", "Lower straight down, not forward"],
    steps: [
      "Stand a stride length in front of a bench and place the top of one foot on it behind you.",
      "Adjust until the front shin can stay near vertical at the bottom.",
      "Lower straight down by bending the front knee, letting the back knee travel toward the floor.",
      "Keep your chest tall and your hips square; do not lean over the front leg.",
      "Drive through the front heel back to the top, then repeat.",
    ],
    defaults: reps(3, 8, 75),
  }),

  /* ---------------- horizontal push (the bodyweight ladder) ---------------- */
  ex("Wall_Push-Up", "Wall Push-Up", {
    pattern: "horizontal-push",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    chainId: "push-bw",
    chainRank: 1,
    cues: ["Body in one line from head to heels", "Elbows back at 45 degrees, not flared"],
    steps: [
      "Stand an arm's length from a wall and place both hands on it at chest height.",
      "Set your hands a little wider than your shoulders.",
      "Keep your body in one line from head to heels and brace your midsection.",
      "Bend the elbows to about forty-five degrees and bring your chest toward the wall.",
      "Press back to full arm's length without letting the hips sag or pike.",
    ],
    defaults: reps(2, 12, 45),
  }),
  ex("Knee_Push-Up", "Knee Push-Up", {
    pattern: "horizontal-push",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    contraindications: ["wrists"],
    chainId: "push-bw",
    chainRank: 3,
    cues: ["Hips forward so the line stays straight", "Chest to the floor, not the chin"],
    steps: [
      "Kneel down and place your hands a little wider than shoulder width on the floor.",
      "Walk the knees back until your hips, shoulders and knees form one straight line.",
      "Brace your midsection and tuck the ribs down.",
      "Lower your chest, not your chin, toward the floor with the elbows at forty-five degrees.",
      "Press back up to full arm's length, keeping that straight line the whole time.",
    ],
    defaults: reps(3, 10, 45),
  }),
  ex("Archer_Push-Up", "Archer Push-Up", {
    pattern: "horizontal-push",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    level: "expert",
    unilateral: true,
    core: false,
    contraindications: ["wrists", "shoulders"],
    chainId: "push-bw",
    chainRank: 6,
    cues: ["Straight arm stays locked and wide", "Lower to the working side only"],
    steps: [
      "Set up in a push-up position with your hands much wider than your shoulders.",
      "Shift your weight over one hand as you bend that elbow.",
      "Keep the other arm straight and let it slide out wide as you lower.",
      "Bring the chest down toward the working hand only.",
      "Press back to the middle and repeat on the other side.",
    ],
    defaults: reps(3, 5, 90),
  }),

  /* ---------------- vertical push (the gap the dataset leaves) ---------------- */
  ex("Pike_Push-Up", "Pike Push-Up", {
    pattern: "vertical-push",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps"],
    level: "intermediate",
    contraindications: ["shoulders", "wrists"],
    chainId: "vpush-bw",
    chainRank: 2,
    cues: ["Hips high, head between the hands", "Crown of the head to the floor"],
    steps: [
      "Start in a push-up position, then walk your feet in and push your hips high.",
      "Your body should look like an upside-down V with straight arms and legs.",
      "Bend the elbows and lower the crown of your head toward the floor between your hands.",
      "Keep the elbows tracking forward rather than flaring straight out.",
      "Press back up until the arms are fully long.",
    ],
    defaults: reps(3, 8, 60),
  }),
  ex("Incline_Pike_Push-Up", "Incline Pike Push-Up", {
    pattern: "vertical-push",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps"],
    contraindications: ["shoulders", "wrists"],
    chainId: "vpush-bw",
    chainRank: 1,
    cues: ["Hands on the floor, feet on a step", "Press straight up, ears past the arms"],
    steps: [
      "Place your hands on the floor and your feet on a step or low box.",
      "Push the hips high so your torso is close to vertical.",
      "Lower the crown of your head toward the floor between your hands.",
      "Keep the midsection braced so the lower back does not arch.",
      "Press straight up until your ears pass your arms.",
    ],
    defaults: reps(3, 10, 60),
  }),
  ex("Band_Overhead_Press", "Band Overhead Press", {
    pattern: "vertical-push",
    requires: ["bands"],
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps"],
    contraindications: ["shoulders"],
    cues: ["Stand on the band, brace the ribs down", "Press until the arms are fully long"],
    steps: [
      "Stand on the middle of the band with your feet hip width apart.",
      "Hold a handle in each hand at shoulder height, palms facing forward.",
      "Brace your midsection and pull your ribs down so you do not lean back.",
      "Press the handles straight up until the arms are fully long.",
      "Lower under control back to shoulder height.",
    ],
    defaults: reps(3, 12, 60),
  }),

  /* ---------------- band work ----------------
     Owning bands must actually change the plan. Without a band option for the
     leg and press patterns, a "bands only" setup generates the same session as
     owning nothing at all. */
  ex("Band_Squat", "Band Squat", {
    pattern: "squat",
    requires: ["bands"],
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["glutes"],
    contraindications: ["knees"],
    cues: ["Stand on the band, handles at the shoulders", "Sit down between the hips, chest tall"],
    steps: [
      "Stand on the middle of the band with your feet shoulder width apart.",
      "Bring the handles up to your shoulders, elbows in front of you.",
      "Take a breath and brace, then sit down between your hips.",
      "Keep your chest tall and your knees tracking out over your toes.",
      "Drive through the whole foot to stand, keeping tension on the band.",
    ],
    defaults: reps(3, 14, 60),
  }),
  ex("Band_Romanian_Deadlift", "Band Romanian Deadlift", {
    pattern: "hinge",
    requires: ["bands"],
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["glutes"],
    cues: ["Stand on the band, hinge from the hips", "Keep tension the whole way up"],
    steps: [
      "Stand on the middle of the band with your feet hip width apart, a handle in each hand.",
      "Stand tall, then take a breath and brace your midsection.",
      "Push your hips straight back, letting the handles travel down your thighs.",
      "Keep your back flat and your shins near vertical.",
      "Stop when the hamstrings tighten, then drive the hips forward to stand tall.",
    ],
    defaults: reps(3, 14, 60),
  }),
  ex("Band_Chest_Press", "Band Chest Press", {
    pattern: "horizontal-push",
    requires: ["bands"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    cues: ["Anchor the band behind you at chest height", "Press to full length, resist coming back"],
    steps: [
      "Anchor the band behind you at about chest height and take a handle in each hand.",
      "Step forward until there is tension, one foot slightly ahead for balance.",
      "Start with the handles beside your chest, elbows at about forty-five degrees.",
      "Press both handles forward until the arms are fully long.",
      "Resist the band on the way back rather than letting it snap you in.",
    ],
    defaults: reps(3, 14, 60),
  }),
  ex("Band_Woodchop", "Band Woodchop", {
    pattern: "rotation",
    requires: ["bands"],
    primaryMuscles: ["abdominals"],
    secondaryMuscles: ["shoulders"],
    unilateral: true,
    contraindications: ["lower-back"],
    cues: ["Turn from the ribs, hips stay quiet", "Arms stay long, let the trunk do it"],
    steps: [
      "Anchor the band low to one side and hold the handle in both hands.",
      "Stand with your feet shoulder width apart, side-on to the anchor.",
      "Keep your arms long and your hips facing forward.",
      "Turn from the ribs and pull the handle up and across to the opposite shoulder.",
      "Return slowly along the same path, letting the trunk do the work.",
    ],
    defaults: reps(2, 12, 45),
  }),

  /* ---------------- horizontal pull (near-empty at bodyweight) ---------------- */
  ex("Doorway_Row", "Doorway Row", {
    pattern: "horizontal-pull",
    primaryMuscles: ["middle-back"],
    secondaryMuscles: ["biceps", "lats"],
    cues: ["Grip both sides of a solid doorframe", "Lean back, pull the chest to the frame"],
    steps: [
      "Grip both sides of a solid doorframe at about chest height.",
      "Walk your feet forward and lean back with your arms straight.",
      "Keep your body in one line from head to heels and brace your midsection.",
      "Pull your chest toward the frame, driving the elbows past your ribs.",
      "Squeeze the shoulder blades together, then lower under control.",
    ],
    defaults: reps(3, 12, 60),
  }),
  ex("Band_Row", "Band Row", {
    pattern: "horizontal-pull",
    requires: ["bands"],
    primaryMuscles: ["middle-back"],
    secondaryMuscles: ["biceps", "lats"],
    cues: ["Pull the elbows past the ribs", "Shoulder blades together at the end"],
    steps: [
      "Anchor the band at about waist height, or sit and loop it around your feet.",
      "Hold a handle in each hand with your arms long and a little tension already on.",
      "Sit or stand tall with your chest up and your shoulders down.",
      "Pull the elbows straight back past your ribs.",
      "Squeeze the shoulder blades together at the end, then return slowly.",
    ],
    defaults: reps(3, 14, 60),
  }),
  ex("Band_Pull-Apart", "Band Pull-Apart", {
    pattern: "horizontal-pull",
    requires: ["bands"],
    primaryMuscles: ["middle-back"],
    secondaryMuscles: ["shoulders"],
    mechanic: "isolation",
    cues: ["Arms long, lead with the knuckles", "Slow all the way back to the front"],
    steps: [
      "Hold the band in both hands at shoulder height with your arms straight out in front.",
      "Set your hands about shoulder width apart so there is light tension.",
      "Keep the arms long and lead with the knuckles.",
      "Pull the band apart until your arms are out in a wide T.",
      "Return all the way to the front slowly rather than letting it snap back.",
    ],
    defaults: reps(2, 15, 45),
  }),

  /* ---------------- vertical pull ---------------- */
  ex("Band_Lat_Pulldown", "Band Lat Pulldown", {
    pattern: "vertical-pull",
    requires: ["bands"],
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps"],
    cues: ["Anchor the band high and kneel", "Drive the elbows down to the ribs"],
    steps: [
      "Anchor the band high, over a door or a bar, and kneel underneath it.",
      "Take a handle in each hand with the arms fully long overhead.",
      "Sit tall and brace so your lower back does not arch.",
      "Drive the elbows down toward your ribs, pulling the hands to shoulder height.",
      "Let the band lift the arms back up slowly, keeping tension throughout.",
    ],
    defaults: reps(3, 14, 60),
  }),
  ex("Dead_Hang", "Dead Hang", {
    pattern: "vertical-pull",
    requires: ["pullup-bar"],
    kind: "time",
    primaryMuscles: ["forearms"],
    secondaryMuscles: ["lats"],
    contraindications: ["shoulders"],
    chainId: "vpull-bw",
    chainRank: 1,
    cues: ["Shoulders active, not hanging slack", "Breathe; relax everything below the ribs"],
    steps: [
      "Reach up and take an overhand grip on the bar, hands about shoulder width apart.",
      "Step or hop off and let your body hang with your arms long.",
      "Pull your shoulders down away from your ears so you are not hanging slack.",
      "Keep your legs together and let everything below the ribs relax.",
      "Breathe steadily for the full hold, then step down under control.",
    ],
    defaults: time(3, 25, 60),
  }),
  ex("Negative_Pull-Up", "Negative Pull-Up", {
    pattern: "vertical-pull",
    requires: ["pullup-bar"],
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps", "middle-back"],
    level: "intermediate",
    contraindications: ["shoulders"],
    chainId: "vpull-bw",
    chainRank: 2,
    cues: ["Jump to the top, then lower slowly", "Aim for a five second descent"],
    steps: [
      "Set a box or step under the bar so you can reach the top position.",
      "Jump or step up until your chin is over the bar and your chest is close to it.",
      "Take your feet off the support and hold the top for a beat.",
      "Lower yourself as slowly as you can, aiming for about five seconds.",
      "Reach a full hang, then step back up for the next rep rather than dropping.",
    ],
    defaults: reps(3, 5, 90),
  }),

  /* ---------------- carry ---------------- */
  ex("Suitcase_Carry", "Suitcase Carry", {
    pattern: "carry",
    requires: ["dumbbells"],
    kind: "time",
    primaryMuscles: ["abdominals"],
    secondaryMuscles: ["traps", "forearms"],
    unilateral: true,
    spaceNeeded: "normal",
    cues: ["One weight only, stay perfectly upright", "Resist the lean; that is the whole exercise"],
    steps: [
      "Set one weight on the floor beside you.",
      "Hinge down, take the handle, and stand up with a flat back.",
      "Stand perfectly upright with the shoulders level, resisting the pull to one side.",
      "Brace your midsection and walk with short, quick steps.",
      "Keep the free arm relaxed at your side; do not use it as a counterweight.",
    ],
    defaults: time(2, 60, 45),
  }),

  /* ---------------- core ---------------- */
  ex("Bird_Dog", "Bird Dog", {
    pattern: "core-brace",
    kind: "time",
    primaryMuscles: ["abdominals"],
    secondaryMuscles: ["lower-back", "glutes"],
    unilateral: true,
    cues: ["Reach opposite arm and leg long", "Keep the hips square to the floor"],
    steps: [
      "Start on your hands and knees with the hands under the shoulders and knees under the hips.",
      "Brace your midsection so the lower back stays flat, not arched.",
      "Reach one arm forward and the opposite leg back until both are long.",
      "Keep your hips square to the floor and your neck in line with your spine.",
      "Hold, breathing steadily, then switch to the other pair.",
    ],
    defaults: time(2, 40, 30),
  }),
  ex("Hollow_Hold", "Hollow Hold", {
    pattern: "core-brace",
    kind: "time",
    primaryMuscles: ["abdominals"],
    level: "intermediate",
    contraindications: ["lower-back", "neck"],
    cues: ["Press the lower back into the floor", "Lower the legs only as far as that holds"],
    steps: [
      "Lie on your back with your arms overhead and your legs straight.",
      "Press your lower back firmly into the floor and keep it there.",
      "Lift your shoulders and legs a few inches off the floor.",
      "Lower the legs only as far as you can keep the lower back pressed down.",
      "Breathe shallowly and steadily; bend the knees if the back lifts.",
    ],
    defaults: time(3, 30, 45),
  }),

  /* ---------------- warm-up / mobility ---------------- */
  ex("Leg_Swings", "Leg Swings", {
    pattern: "mobility",
    kind: "time",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["glutes"],
    mechanic: null,
    unilateral: true,
    cues: ["Hold something solid for balance", "Swing only as high as stays relaxed"],
    steps: [
      "Stand side-on to a wall or post and hold it for balance.",
      "Stand tall on the supporting leg with a soft knee.",
      "Swing the free leg forward and back in a relaxed arc.",
      "Let the range grow gradually rather than forcing the first swing high.",
      "Keep your torso upright and still; only the leg moves.",
    ],
    defaults: time(1, 40, 20),
  }),
  ex("Cat_Cow", "Cat Cow", {
    pattern: "mobility",
    kind: "time",
    primaryMuscles: ["lower-back"],
    secondaryMuscles: ["abdominals"],
    mechanic: null,
    cues: ["Move one vertebra at a time", "Let the breath set the pace"],
    steps: [
      "Start on your hands and knees, hands under the shoulders, knees under the hips.",
      "Breathe out and round your back one vertebra at a time, tucking the tailbone.",
      "Let your head drop naturally at the end of the round.",
      "Breathe in and reverse it, arching from the tailbone up to the neck.",
      "Let the breath set the pace rather than rushing the shape.",
    ],
    defaults: time(1, 40, 20),
  }),
  ex("Hip_Circles", "Hip Circles", {
    pattern: "mobility",
    kind: "time",
    primaryMuscles: ["glutes"],
    mechanic: null,
    cues: ["Hands on hips, feet planted wide", "Draw the biggest circle you can"],
    steps: [
      "Stand with your feet a little wider than your shoulders and your hands on your hips.",
      "Keep your feet planted and your chest facing forward.",
      "Push the hips out to one side and start circling them.",
      "Draw the biggest circle you can without moving the feet or the shoulders.",
      "Do half the time in one direction, then reverse.",
    ],
    defaults: time(1, 30, 20),
  }),
  ex("Shoulder_Rolls", "Shoulder Rolls", {
    pattern: "mobility",
    kind: "time",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["traps"],
    mechanic: null,
    cues: ["Big, slow circles backwards", "Let the arms stay heavy"],
    steps: [
      "Stand tall with your arms hanging heavy at your sides.",
      "Lift both shoulders up toward your ears.",
      "Roll them back and squeeze the shoulder blades together.",
      "Let them drop down and forward to complete a big, slow circle.",
      "Do half the time rolling backwards, then reverse the direction.",
    ],
    defaults: time(1, 25, 20),
  }),
  ex("Torso_Twist", "Standing Torso Twist", {
    pattern: "mobility",
    kind: "time",
    primaryMuscles: ["abdominals"],
    secondaryMuscles: ["lower-back"],
    mechanic: null,
    contraindications: ["lower-back"],
    cues: ["Turn from the ribs, hips facing forward", "Let the arms swing loosely"],
    steps: [
      "Stand with your feet shoulder width apart and your knees soft.",
      "Let your arms hang loose or fold them across your chest.",
      "Keep your hips and feet facing forward.",
      "Turn from the ribs to one side, letting the arms swing with you.",
      "Come back through the middle and turn to the other side in a steady rhythm.",
    ],
    defaults: time(1, 30, 20),
  }),
];
